name: flutter_soloud
description: >-
  A low-level audio plugin for Flutter,
  mainly meant for games and immersive apps.
  Based on the SoLoud (C++) audio engine.
version: 2.1.0
issue_tracker: https://github.com/alnitak/flutter_soloud/issues
homepage: https://github.com/alnitak/flutter_soloud
maintainer: Marco Bavagnoli (@lildeimos)
platforms:
  android:
  ios:
  linux:
  macos:
  windows:
topics:
  - audio
  - player
  - games

screenshots:
  - description: "audio FFT data"
    path: img/screenshot.png

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  http: ^1.2.1
  logging: ^1.2.0
  meta: ^1.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  plugin_platform_interface: ^2.0.2
  web: ^0.5.1

dev_dependencies:
  ffigen: ^12.0.0
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  very_good_analysis: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true

  assets:
    # These assets are only needed for the web platform.
    # Waiting for https://github.com/flutter/flutter/issues/65065 and
    # https://github.com/flutter/flutter/issues/8230 to be addressed.
    # to make a conditional build.
    - web/worker.dart.js
    - web/libflutter_soloud_plugin.js
    - web/libflutter_soloud_plugin.wasm
